<script>
	try {
		var x = eval('1 <> 2');
	}
	catch(err) {
		console.log(err.message);
	}
</script>